version: "3"

services:
  ray-head:
    image: ${RAY_IMAGE}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
      - "${HEADNODE_PORT}:${HEADNODE_PORT}"
    env_file:
      - .env
    command: bash -c "ray start --head --dashboard-port=${DASHBOARD_PORT} --port=${REDIS_PORT} --dashboard-host=0.0.0.0 --block"
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2g"
    networks:
      - ray_net

  ray-worker:
    image: ${RAY_IMAGE}
    depends_on:
      - ray-head
    env_file:
      - .env
    command: bash -c "ray start --address=ray-head:${REDIS_PORT} --num-cpus=${NUM_CPU_WORKER} --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: ${NUM_WORKERS}
      resources:
        limits:
          cpus: ${NUM_CPU_WORKER}
          memory: "2g"
    networks:
      - ray_net

networks:
  ray_net:
    ipam:
      driver: default
      config:
        - subnet: 172.65.0.0/16
